- id: WebHook_BedtimeShutdown
  alias: Webhook - Bedtime Shutdown
  description: ''
  trigger:
  - platform: webhook
    webhook_id: bedtime_shutdown
  condition: []
  action:
  - service: script.bedtime_script
- id: WebHook_MasterMovies
  alias: Webhook - Master Movies
  description: ''
  trigger:
  - platform: webhook
    webhook_id: master_movies
  condition: []
  action:
  - service: script.master_movies_script
- id: GarageOpening
  alias: GarageDoorOpening
  description: ''
  trigger:
  - entity_id: cover.main_garage
    platform: state
    to: open
  - entity_id: cover.main_garage
    platform: state
    to: opening
  - entity_id: cover.3rd_car_garage
    platform: state
    to: open
  - entity_id: cover.3rd_car_garage
    platform: state
    to: opening
  condition: []
  action:
  - alias: ''
    data: {}
    entity_id: switch.780740202cf432ca424e
    service: switch.turn_on
- id: GarageClosing
  alias: GarageClosing
  description: ''
  trigger:
  - entity_id: cover.main_garage
    platform: state
    to: closing
  - entity_id: cover.main_garage
    platform: state
    to: closed
  - entity_id: cover.3rd_car_garage
    platform: state
    to: closing
  - entity_id: cover.3rd_car_garage
    platform: state
    to: closed
  condition: []
  action:
  - entity_id: switch.780740202cf432ca424e
    service: switch.turn_off
- id: Sunrise_Trigger_Minus_1_Hour
  alias: Sunrise - 1 hour before
  description: ''
  trigger:
  - event: sunrise
    offset: -01:00:00
    platform: sun
  condition: []
  action:
  - entity_id: switch.railing_lights
    service: switch.turn_on
  - data: {}
    entity_id: switch.curtain_lights
    service: switch.turn_on
- id: Sunset_Trigger_Minus_15_Minutes
  alias: Sunset - 15 Minutes Before
  trigger:
  - event: sunset
    offset: -00:15:00
    platform: sun
  action:
  - entity_id: switch.06200180bcddc2e5e01d
    service: script.1582169197516
- id: Weekday_Dad_Good_Morning
  alias: Weekday - Dad Triggers
  description: ''
  trigger:
  - at: 08:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.dad_alarm_script
- id: Weekday_Austin_Good_Morning
  alias: Weekday - Austin Triggers
  description: ''
  trigger:
  - at: 07:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - entity_id: switch.03200076dc4f2222957e
    service: script.1583846065286
- id: Weekend_Austin_Good_Morning
  alias: Weekend - Austin Morning Triggers
  description: ''
  trigger:
  - at: '9:30'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - entity_id: switch.03200076dc4f2222957e
    service: script.1583846065286
- id: Austin_Bedtime
  alias: Bedtime - Austin
  description: ''
  trigger:
  - at: '22:45'
    platform: time
  condition: []
  action:
  - entity_id: switch.03200076dc4f2222957e
    service: switch.turn_off
- id: Ring_Button_Pushed
  alias: Ring - Button Pushed
  description: ''
  trigger:
  - device_id: 2469248b20bf42a48c0e5993d50d668d
    domain: binary_sensor
    entity_id: binary_sensor.front_door_ding
    for:
      hours: 0
      minutes: 0
      seconds: 0
    platform: device
    type: occupied
  condition: []
  action:
  - delay: ''
- id: timer_bathroomfan_powder-end
  alias: Timer-BathroomFan-Powder-End
  description: ''
  trigger:
  - entity_id: timer.powder_bathroom_fan
    platform: state
    to: finished
  - entity_id: timer.powder_bathroom_fan
    platform: state
    to: idle
  condition: []
  action:
  - data: {}
    entity_id: switch.powder_bathroom_fan
    service: switch.turn_off
- id: timer_bathroomfan_powder-start
  alias: Timer-BathroomFan-Powder-Start
  description: ''
  trigger:
  - entity_id: switch.powder_fan
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: timer.powder_bathroom_fan
    service: timer.start
- id: timer_bathroomfan_kids-end
  alias: Timer-BathroomFan-Kids-End
  description: ''
  trigger:
  - entity_id: timer.kids_bathroom_fan
    platform: state
    to: finished
  - entity_id: timer.kids_bathroom_fan
    platform: state
    to: idle
  condition: []
  action:
  - data: {}
    entity_id: switch.kids_bathroom_fan
    service: switch.turn_off
- id: timer_bathroomfan_kids-start
  alias: Timer-BathroomFan-Kids-Start
  description: ''
  trigger:
  - entity_id: switch.kids_bathroom_fan
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: timer.kids_bathroom_fan
    service: timer.start
- id: timer_dadslamp-end
  alias: Timer-Dads-Lamp-End
  description: ''
  trigger:
  - entity_id: timer.dads_lamp
    platform: state
    to: finished
  - entity_id: timer.dads_lamp
    platform: state
    to: idle
  condition: []
  action:
  - data: {}
    entity_id: light.dads_lamp
    service: switch.turn_off
- id: timer_dadslamp-start
  alias: Timer-Dads-Lamp-Start
  description: ''
  trigger:
  - entity_id: light.dads_lamp
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: timer.dads_lamp
    service: timer.start
