- id: WebHook_BedtimeShutdown
  alias: Webhook - Bedtime Shutdown
  description: ''
  trigger:
  - platform: webhook
    webhook_id: bedtime_shutdown
  condition: []
  action:
  - service: script.bedtime_script
- id: WebHook_MasterMovies
  alias: Webhook - Master Movies
  description: ''
  trigger:
  - platform: webhook
    webhook_id: master_movies
  condition: []
  action:
  - service: script.master_movies_script
- id: GarageOpening
  alias: GarageDoorOpening
  description: ''
  trigger:
  - entity_id: cover.main_garage
    platform: state
    to: open
  - entity_id: cover.main_garage
    platform: state
    to: opening
  - entity_id: cover.3rd_car_garage
    platform: state
    to: open
  - entity_id: cover.3rd_car_garage
    platform: state
    to: opening
  condition: []
  action:
  - entity_id: switch.garagelights_garage_lights
    service: switch.turn_on
  - entity_id: switch.garagelamp_garage_lamp
    service: switch.turn_on
- id: GarageClosing
  alias: GarageClosing
  description: ''
  trigger:
  - entity_id: cover.main_garage
    platform: state
    to: closing
  - entity_id: cover.main_garage
    platform: state
    to: closed
  - entity_id: cover.3rd_car_garage
    platform: state
    to: closing
  - entity_id: cover.3rd_car_garage
    platform: state
    to: closed
  condition: []
  action:
  - entity_id: switch.garagelights_garage_lights
    service: switch.turn_off
  - entity_id: switch.garagelamp_garage_lamp
    service: switch.turn_off
- id: Sunrise_Trigger_Minus_1_Hour
  alias: Sunrise - 1 hour before
  description: ''
  trigger:
  - event: sunrise
    offset: -01:00:00
    platform: sun
  condition: []
  action:
  - entity_id: switch.railinglights_railing_lights
    service: switch.turn_on
  - data: {}
    entity_id: switch.curtainlights_curtain_lights
    service: switch.turn_on
- id: Sunset_Trigger_Minus_15_Minutes
  alias: Sunset - 15 Minutes Before
  trigger:
  - event: sunset
    offset: -00:15:00
    platform: sun
  action:
  - service: script.holiday_lighting_script
- id: Weekday_Dad_Good_Morning
  alias: Weekday - Dad Triggers
  description: ''
  trigger:
  - at: 08:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.dad_alarm_script
- id: Weekday_Austin_Good_Morning
  alias: Weekday - Austin Triggers
  description: ''
  trigger:
  - at: 07:00
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - entity_id: switch.03200076dc4f2222957e
    service: script.austins_alarm_script
- id: Weekend_Austin_Good_Morning
  alias: Weekend - Austin Morning Triggers
  description: ''
  trigger:
  - at: '9:30'
    platform: time
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'off'
  action:
  - entity_id: switch.03200076dc4f2222957e
    service: script.austins_alarm_script
- id: Austin_Bedtime
  alias: Bedtime - Austin
  description: ''
  trigger:
  - at: '22:45'
    platform: time
  condition: []
  action:
  - entity_id: switch.petlights_pet_lights
    service: switch.turn_off
- id: Ring_Button_Pushed
  alias: Ring - Button Pushed
  description: ''
  trigger:
  - device_id: 2469248b20bf42a48c0e5993d50d668d
    domain: binary_sensor
    entity_id: binary_sensor.front_door_ding
    for:
      hours: 0
      minutes: 0
      seconds: 0
    platform: device
    type: occupied
  condition: []
  action:
  - delay: ''
  mode: single
- id: timer_bathroomfan_powder-end
  alias: Timer-BathroomFan-Powder-End
  description: ''
  trigger:
  - entity_id: timer.powder_bathroom_fan
    platform: state
    to: finished
  - entity_id: timer.powder_bathroom_fan
    platform: state
    to: idle
  condition: []
  action:
  - data: {}
    entity_id: switch.powder_fan
    service: switch.turn_off
  mode: single
- id: timer_bathroomfan_powder-start
  alias: Timer-BathroomFan-Powder-Start
  description: ''
  trigger:
  - entity_id: switch.powder_fan
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: timer.powder_bathroom_fan
    service: timer.start
  mode: single
- id: timer_internet_router_restoration-start
  alias: Timer-Internet-Router-Restoration-Start
  description: ''
  trigger:
  - entity_id: switch.internet_router
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    entity_id: timer.internet_router_restoration
    service: timer.start
  mode: single
- id: timer_internet_router_restoration-end
  alias: Timer-Internet-Router-Restoration-End
  description: ''
  trigger:
  - entity_id: timer.internet_router_restoration
    platform: state
    to: finished
  - entity_id: timer.internet_router_restoration
    platform: state
    to: idle
  condition: []
  action:
  - data: {}
    entity_id: switch.internet_router
    service: switch.turn_on
  mode: single
- id: timer_bathroomfan_kids-end
  alias: Timer-BathroomFan-Kids-End
  description: ''
  trigger:
  - entity_id: timer.kids_bathroom_fan
    platform: state
    to: finished
  - entity_id: timer.kids_bathroom_fan
    platform: state
    to: idle
  condition: []
  action:
  - data: {}
    entity_id: switch.kids_bathroom_fan
    service: switch.turn_off
  mode: single
- id: timer_bathroomfan_kids-start
  alias: Timer-BathroomFan-Kids-Start
  description: ''
  trigger:
  - entity_id: switch.kids_bathroom_fan
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: timer.kids_bathroom_fan
    service: timer.start
  mode: single
- id: timer_outdoor-decorations-end
  alias: Timer-Outdoor-Decorations-End
  description: ''
  trigger:
  - entity_id: timer.outdoor_decorations
    platform: state
    to: finished
  - entity_id: timer.outdoor_decorations
    platform: state
    to: idle
  condition: []
  action:
  - data: {}
    entity_id: switch.ground_decor
    service: switch.turn_off
  - data: {}
    entity_id: switch.top_christmas
    service: switch.turn_off
  - data: {}
    entity_id: switch.bottom_christmas
    service: switch.turn_off
  mode: single
- id: timer_outdoor-lights-start
  alias: Timer-Outdoor-Decorations-Start
  description: ''
  trigger:
  - entity_id: switch.ground_decor
    platform: state
    to: 'on'
  - entity_id: switch.top_christmas
    platform: state
    to: 'on'
  - entity_id: switch.bottom_christmas
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: timer.outdoor_decorations
    service: timer.start
  mode: single
- id: timer_dadslamp-end
  alias: Timer-Dads-Lamp-End
  description: ''
  trigger:
  - entity_id: timer.dads_lamp
    platform: state
    to: finished
  - entity_id: timer.dads_lamp
    platform: state
    to: idle
  condition: []
  action:
  - data: {}
    entity_id: switch.dadslamp_dads_lamp
    service: switch.turn_off
- id: timer_dadslamp-start
  alias: Timer-Dads-Lamp-Start
  description: ''
  trigger:
  - entity_id: switch.dadslamp_dads_lamp
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: timer.dads_lamp
    service: timer.start
- id: iOS_Bedtime_Widget
  alias: iOS - Bedtime Widget
  description: ''
  trigger:
  - event_data:
      actionName: Bedtime
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data: {}
    service: script.bedtime_script
- id: iOS_MasterMovies_Widget
  alias: iOS - Master Movies Widget
  description: ''
  trigger:
  - event_data:
      actionName: Master Movies
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data: {}
    service: script.master_movies_script
- id: iOS_FrontLights_Widget
  alias: iOS - Front Lights Widget
  description: ''
  trigger:
  - event_data:
      actionName: Exterior Front Lights
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data: {}
    service: script.turn_on_exterior_front_lights
- id: iOS_GarageClose_Widget
  alias: iOS - Garage Close Widget
  description: ''
  trigger:
  - event_data:
      actionName: Close Garages
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: cover.main_garage
    service: cover.close_cover
  - data: {}
    entity_id: cover.3rd_car_garage
    service: cover.close_cover
- id: iOS_Garage_OpenMain_Widget
  alias: iOS - Garage Open Main Widget
  description: ''
  trigger:
  - event_data:
      actionName: Open Main Garage
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: cover.main_garage
    service: cover.open_cover
- id: iOS_Garage_Open3rdCar_Widget
  alias: iOS - Garage Open 3rd Car Widget
  description: ''
  trigger:
  - event_data:
      actionName: Open 3rd Car
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: cover.3rd_car_garage
    service: cover.open_cover
