services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    environment:
      TZ: 'America/Denver'
    volumes:
      - '../data/homeassistant:/config'
    restart: unless-stopped
    privileged: true
    network_mode: host

  matter:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter
    volumes:
      - ../data/matter:/data
      # Required for Bluetooth via D-Bus
      - /run/dbus:/run/dbus:ro
    security_opt:
      # Needed for Bluetooth via dbus
      - apparmor:unconfined
    restart: always
    network_mode: host

  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ../data/esphome:/config:rw
      - /etc/localtime:/etc/localtime:ro
    restart: no
    network_mode: bridge
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    ports:
      - 6052:6052
