version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    environment:
      TZ: 'America/Denver'
    volumes:
      - '../data/homeassistant:/config'
    restart: unless-stopped
    privileged: true
    network_mode: host

  matter:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter
    volumes:
      - ../data/matter:/data
      # Required for Bluetooth via D-Bus
      - /run/dbus:/run/dbus:ro
    security_opt:
      # Needed for Bluetooth via dbus
      - apparmor:unconfined
    restart: always
    network_mode: host
