services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    environment:
      TZ: 'America/Denver'
    volumes:
      - '../data/homeassistant:/config'
      # Required for Bluetooth via D-Bus
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  matter:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter
    volumes:
      - ../data/matter:/data
      # Required for Bluetooth via D-Bus
      - /run/dbus:/run/dbus:ro
    security_opt:
      # Needed for Bluetooth via dbus
      - apparmor:unconfined
    restart: always
    network_mode: host

  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ../data/esphome:/config:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: bridge
    environment:
      # - PUID=1000
      # - PGID=1000
      # - TZ=Etc/UTC
      - ESPHOME_DASHBOARD_USE_PING=true
    ports:
      - 6052:6052

  # samba:
  #   container_name: samba
  #   image: dperson/samba
  #   restart: unless-stopped
  #   environment:
  #     - USERID=1000
  #     - GROUPID=1000
  #     - TZ=America/Denver
  #   ports:
  #     - "139:139"
  #     - "445:445"
  #   volumes:
  #     - /mnt/m2usb:/share
  #   command: '-s "m2usb;/share;yes;no;no;all;none" -u "user;password" -p'
